name: CI Build

on:
  push:
    branches:
      - dev
      - main
      - actions
      - make-tweaks
      - rename-littlefs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/build
