name: release-workflow

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: echo ${{ github.sha }} > Release-${{ github.ref_name }}.txt
      - name: Test
        run: cat Release-${{ github.ref_name }}.txt
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            Release-${{ github.ref_name }}.txt
            LICENSE